# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yareg/gameApplication

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yareg/gameApplication

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yareg/gameApplication/CMakeFiles /home/yareg/gameApplication//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yareg/gameApplication/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client_app

# Build rule for target.
client_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client_app
.PHONY : client_app

# fast build rule for target.
client_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/build
.PHONY : client_app/fast

#=============================================================================
# Target rules for targets named server_app

# Build rule for target.
server_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server_app
.PHONY : server_app

# fast build rule for target.
server_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_app.dir/build.make CMakeFiles/server_app.dir/build
.PHONY : server_app/fast

#=============================================================================
# Target rules for targets named client_app_autogen_timestamp_deps

# Build rule for target.
client_app_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client_app_autogen_timestamp_deps
.PHONY : client_app_autogen_timestamp_deps

# fast build rule for target.
client_app_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app_autogen_timestamp_deps.dir/build.make CMakeFiles/client_app_autogen_timestamp_deps.dir/build
.PHONY : client_app_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named client_app_autogen

# Build rule for target.
client_app_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client_app_autogen
.PHONY : client_app_autogen

# fast build rule for target.
client_app_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app_autogen.dir/build.make CMakeFiles/client_app_autogen.dir/build
.PHONY : client_app_autogen/fast

#=============================================================================
# Target rules for targets named server_app_autogen_timestamp_deps

# Build rule for target.
server_app_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server_app_autogen_timestamp_deps
.PHONY : server_app_autogen_timestamp_deps

# fast build rule for target.
server_app_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_app_autogen_timestamp_deps.dir/build.make CMakeFiles/server_app_autogen_timestamp_deps.dir/build
.PHONY : server_app_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named server_app_autogen

# Build rule for target.
server_app_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server_app_autogen
.PHONY : server_app_autogen

# fast build rule for target.
server_app_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_app_autogen.dir/build.make CMakeFiles/server_app_autogen.dir/build
.PHONY : server_app_autogen/fast

client/client.o: client/client.cpp.o
.PHONY : client/client.o

# target to build an object file
client/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client/client.cpp.o
.PHONY : client/client.cpp.o

client/client.i: client/client.cpp.i
.PHONY : client/client.i

# target to preprocess a source file
client/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client/client.cpp.i
.PHONY : client/client.cpp.i

client/client.s: client/client.cpp.s
.PHONY : client/client.s

# target to generate assembly for a file
client/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client/client.cpp.s
.PHONY : client/client.cpp.s

client/main.o: client/main.cpp.o
.PHONY : client/main.o

# target to build an object file
client/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client/main.cpp.o
.PHONY : client/main.cpp.o

client/main.i: client/main.cpp.i
.PHONY : client/main.i

# target to preprocess a source file
client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client/main.cpp.i
.PHONY : client/main.cpp.i

client/main.s: client/main.cpp.s
.PHONY : client/main.s

# target to generate assembly for a file
client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client/main.cpp.s
.PHONY : client/main.cpp.s

client/ui/gamewindow/gamewindow.o: client/ui/gamewindow/gamewindow.cpp.o
.PHONY : client/ui/gamewindow/gamewindow.o

# target to build an object file
client/ui/gamewindow/gamewindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client/ui/gamewindow/gamewindow.cpp.o
.PHONY : client/ui/gamewindow/gamewindow.cpp.o

client/ui/gamewindow/gamewindow.i: client/ui/gamewindow/gamewindow.cpp.i
.PHONY : client/ui/gamewindow/gamewindow.i

# target to preprocess a source file
client/ui/gamewindow/gamewindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client/ui/gamewindow/gamewindow.cpp.i
.PHONY : client/ui/gamewindow/gamewindow.cpp.i

client/ui/gamewindow/gamewindow.s: client/ui/gamewindow/gamewindow.cpp.s
.PHONY : client/ui/gamewindow/gamewindow.s

# target to generate assembly for a file
client/ui/gamewindow/gamewindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client/ui/gamewindow/gamewindow.cpp.s
.PHONY : client/ui/gamewindow/gamewindow.cpp.s

client/ui/mainwindow/mainwindow.o: client/ui/mainwindow/mainwindow.cpp.o
.PHONY : client/ui/mainwindow/mainwindow.o

# target to build an object file
client/ui/mainwindow/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client/ui/mainwindow/mainwindow.cpp.o
.PHONY : client/ui/mainwindow/mainwindow.cpp.o

client/ui/mainwindow/mainwindow.i: client/ui/mainwindow/mainwindow.cpp.i
.PHONY : client/ui/mainwindow/mainwindow.i

# target to preprocess a source file
client/ui/mainwindow/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client/ui/mainwindow/mainwindow.cpp.i
.PHONY : client/ui/mainwindow/mainwindow.cpp.i

client/ui/mainwindow/mainwindow.s: client/ui/mainwindow/mainwindow.cpp.s
.PHONY : client/ui/mainwindow/mainwindow.s

# target to generate assembly for a file
client/ui/mainwindow/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client/ui/mainwindow/mainwindow.cpp.s
.PHONY : client/ui/mainwindow/mainwindow.cpp.s

client_app_autogen/mocs_compilation.o: client_app_autogen/mocs_compilation.cpp.o
.PHONY : client_app_autogen/mocs_compilation.o

# target to build an object file
client_app_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client_app_autogen/mocs_compilation.cpp.o
.PHONY : client_app_autogen/mocs_compilation.cpp.o

client_app_autogen/mocs_compilation.i: client_app_autogen/mocs_compilation.cpp.i
.PHONY : client_app_autogen/mocs_compilation.i

# target to preprocess a source file
client_app_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client_app_autogen/mocs_compilation.cpp.i
.PHONY : client_app_autogen/mocs_compilation.cpp.i

client_app_autogen/mocs_compilation.s: client_app_autogen/mocs_compilation.cpp.s
.PHONY : client_app_autogen/mocs_compilation.s

# target to generate assembly for a file
client_app_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_app.dir/build.make CMakeFiles/client_app.dir/client_app_autogen/mocs_compilation.cpp.s
.PHONY : client_app_autogen/mocs_compilation.cpp.s

gameServer/gameServer.o: gameServer/gameServer.cpp.o
.PHONY : gameServer/gameServer.o

# target to build an object file
gameServer/gameServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_app.dir/build.make CMakeFiles/server_app.dir/gameServer/gameServer.cpp.o
.PHONY : gameServer/gameServer.cpp.o

gameServer/gameServer.i: gameServer/gameServer.cpp.i
.PHONY : gameServer/gameServer.i

# target to preprocess a source file
gameServer/gameServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_app.dir/build.make CMakeFiles/server_app.dir/gameServer/gameServer.cpp.i
.PHONY : gameServer/gameServer.cpp.i

gameServer/gameServer.s: gameServer/gameServer.cpp.s
.PHONY : gameServer/gameServer.s

# target to generate assembly for a file
gameServer/gameServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_app.dir/build.make CMakeFiles/server_app.dir/gameServer/gameServer.cpp.s
.PHONY : gameServer/gameServer.cpp.s

gameServer/main.o: gameServer/main.cpp.o
.PHONY : gameServer/main.o

# target to build an object file
gameServer/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_app.dir/build.make CMakeFiles/server_app.dir/gameServer/main.cpp.o
.PHONY : gameServer/main.cpp.o

gameServer/main.i: gameServer/main.cpp.i
.PHONY : gameServer/main.i

# target to preprocess a source file
gameServer/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_app.dir/build.make CMakeFiles/server_app.dir/gameServer/main.cpp.i
.PHONY : gameServer/main.cpp.i

gameServer/main.s: gameServer/main.cpp.s
.PHONY : gameServer/main.s

# target to generate assembly for a file
gameServer/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_app.dir/build.make CMakeFiles/server_app.dir/gameServer/main.cpp.s
.PHONY : gameServer/main.cpp.s

server_app_autogen/mocs_compilation.o: server_app_autogen/mocs_compilation.cpp.o
.PHONY : server_app_autogen/mocs_compilation.o

# target to build an object file
server_app_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_app.dir/build.make CMakeFiles/server_app.dir/server_app_autogen/mocs_compilation.cpp.o
.PHONY : server_app_autogen/mocs_compilation.cpp.o

server_app_autogen/mocs_compilation.i: server_app_autogen/mocs_compilation.cpp.i
.PHONY : server_app_autogen/mocs_compilation.i

# target to preprocess a source file
server_app_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_app.dir/build.make CMakeFiles/server_app.dir/server_app_autogen/mocs_compilation.cpp.i
.PHONY : server_app_autogen/mocs_compilation.cpp.i

server_app_autogen/mocs_compilation.s: server_app_autogen/mocs_compilation.cpp.s
.PHONY : server_app_autogen/mocs_compilation.s

# target to generate assembly for a file
server_app_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_app.dir/build.make CMakeFiles/server_app.dir/server_app_autogen/mocs_compilation.cpp.s
.PHONY : server_app_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... client_app_autogen"
	@echo "... client_app_autogen_timestamp_deps"
	@echo "... server_app_autogen"
	@echo "... server_app_autogen_timestamp_deps"
	@echo "... client_app"
	@echo "... server_app"
	@echo "... client/client.o"
	@echo "... client/client.i"
	@echo "... client/client.s"
	@echo "... client/main.o"
	@echo "... client/main.i"
	@echo "... client/main.s"
	@echo "... client/ui/gamewindow/gamewindow.o"
	@echo "... client/ui/gamewindow/gamewindow.i"
	@echo "... client/ui/gamewindow/gamewindow.s"
	@echo "... client/ui/mainwindow/mainwindow.o"
	@echo "... client/ui/mainwindow/mainwindow.i"
	@echo "... client/ui/mainwindow/mainwindow.s"
	@echo "... client_app_autogen/mocs_compilation.o"
	@echo "... client_app_autogen/mocs_compilation.i"
	@echo "... client_app_autogen/mocs_compilation.s"
	@echo "... gameServer/gameServer.o"
	@echo "... gameServer/gameServer.i"
	@echo "... gameServer/gameServer.s"
	@echo "... gameServer/main.o"
	@echo "... gameServer/main.i"
	@echo "... gameServer/main.s"
	@echo "... server_app_autogen/mocs_compilation.o"
	@echo "... server_app_autogen/mocs_compilation.i"
	@echo "... server_app_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

