set(__QT_DEPLOY_TARGET_client_app_FILE /home/yareg/gameApplication/client_app)
set(__QT_DEPLOY_TARGET_client_app_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_server_app_FILE /home/yareg/gameApplication/server_app)
set(__QT_DEPLOY_TARGET_server_app_TYPE EXECUTABLE)
